name: heart-disease-kaggle
channels:
  - conda-forge
dependencies:
  - python=3.11
  - xgboost
  - catboost
  - pip
  - pip:
      - mlflow>=2.10
      - scikit-learn>=1.4
      - pandas>=2.2
      - pyyaml>=6.0
      - optuna>=3.6
      - optuna-integration[xgboost,catboost]